linters-settings:
  gocyclo:
    min-complexity: 30
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: US
  lll:
    line-length: 160
  gocognit:
    min-complexity: 20
  gocritic:
    disabled-tags:
    - opinionated
    - experimental
  funlen:
    lines: 150
    statements: 50
  nakedret:
    max-func-lines: 40

linters:
  disable-all: true
  enable:
  - revive
  - bodyclose
  - dogsled
  - dupl
  - errcheck
  - funlen
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - gofmt
  - goimports
  - gosec
  - gosimple
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - copyloopvar
  - staticcheck
  - stylecheck
  - typecheck
  - unconvert
  - unused
  - whitespace

run:
  tests: false

issues:
  exclude-rules:
  - path: test
    linters:
    - dupl
    - gosec
    - funlen
    - gocyclo
  - path: test\.go
    linters:
    - dupl
    - gosec
    - funlen
    - gocyclo
